//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChordKeys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChordKeys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ae::æ
        ///AE::Æ
        ///oe::œ
        ///OE::Œ
        ///sz::ß
        ///SZ::ẞ
        ///
        ///4e::€
        ///4l::₤
        ///
        ///,&apos;::‹
        ///.&apos;::›
        ///&lt;&quot;::«
        ///&gt;&quot;::»
        ///
        ///&apos;a::á
        ///&apos;e::é
        ///&apos;i::í
        ///&apos;o::ó
        ///&apos;u::ú
        ///&apos;y::ý
        ///
        ///&quot;A::Á
        ///&quot;E::É
        ///&quot;I::Í
        ///&quot;O::Ó
        ///&quot;U::Ú
        ///&quot;Y::Ý
        ///
        ///`a::à
        ///`e::è
        ///`i::ì
        ///`o::ò
        ///`u::ù
        ///`y::ỳ
        ///
        ///~A::À
        ///~E::È
        ///~I::Ì
        ///~O::Ò
        ///~U::Ù
        ///~Y::Ỳ
        ///
        ///;a::ä
        ///;e::ë
        ///;i::ï
        ///;o::ö
        ///;u::ü
        ///;y::ÿ
        ///
        ///:A::Ä
        ///:E::Ë
        ///:I::Ï
        ///:O::Ö
        ///:U::Ü
        ///:Y::Ÿ
        ///
        ///6a::â
        ///6e::ê
        ///6i::î
        ///6o::ô
        ///6u::û
        ///6y::ŷ
        ///
        ///^A::Â
        ///^E::Ê
        ///^I::Î
        ///^O::Ô
        ///^U::Û
        ///^Y::Ŷ
        ///
        ///,c::ç
        ///,s::ş
        ///
        ///&lt;C::Ç
        ///&lt;S::Ş
        ///
        ///-a::ā
        ///-e::ē
        ///-i::ī
        ///-o::ō
        ///-u::ū
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultChordKeyScript {
            get {
                return ResourceManager.GetString("DefaultChordKeyScript", resourceCulture);
            }
        }
    }
}
